/* ============================================================
   TRIP DATA — this is the ONLY file you need to edit.
   All content on the site (schedule, places, info) comes
   from this file.

   The SCHEDULE is the real booked itinerary (20–27 Aug 2026).
   PLACES is the explorer catalog — eat & visit, all cities.

   Schedule item fields:
     time / end – "09:30" (optional)
     title      – what you're doing
     desc       – extra notes (optional)
     cat        – "sight" | "food" | "travel" | "free"
     location   – text for the Maps / Waze buttons (optional)
     tickets    – URL to tickets (optional)
     booked     – true = "Booked" badge, false = "Book ahead"
     url        – website (optional)
     explore    – city name; adds a button that opens the
                  Explore section filtered to that city

   Place fields:
     name, city ("Amsterdam" | "Utrecht" | "Zandvoort"),
     kind ("eat" | "visit"), category (free text, used as filter),
     area, price ("€" | "€€" | "€€€", eat only),
     tags [array], desc,
     lat / lng  – coordinates for the distance features,
     img        – image URL shown on the card (optional),
     hours      – opening hours text shown with a clock (optional),
     location   – text for Maps/Waze, url, tickets (optional).
     Places without a url get an automatic 🔍 Google button.

   All times are LOCAL to where we are at that moment.
   ============================================================ */

const TRIP = {
  title: "Amsterdam",
  subtitle: "Family trip — the plan, the tickets, the food. All in one place.",

  hotel: {
    name: "The Social Hub Amsterdam City",
    location: "The Social Hub Amsterdam City, Wibautstraat 129, Amsterdam",
    url: "https://www.thesocialhub.co/amsterdam-city/",
    lat: 52.3547, lng: 4.9114
  },

  days: [
    {
      date: "2026-08-20",
      label: "Day 1",
      theme: "Fly to Amsterdam",
      desc: "Travel day. Times are local: Cyprus time in Cyprus, Dutch time in the Netherlands.",
      items: [
        { time: "13:00", title: "Flight: Larnaca → Amsterdam Schiphol", cat: "travel", booked: true,
          desc: "Departs 13:00 Cyprus time, lands 16:40 Dutch time. Be at the airport ~2h before.",
          location: "Larnaca International Airport" },
        { time: "16:40", title: "Land at Schiphol", cat: "travel",
          desc: "Direct train to Amsterdam Centraal every ~10 min (17 min ride). Tap in/out with any contactless bank card (OVpay).",
          location: "Schiphol Airport" },
        { time: "18:00", title: "Check in — The Social Hub City", cat: "travel", booked: true,
          desc: "Home for the whole week. From Centraal: metro 51/53/54 to Wibautstraat (3 stops), the hotel is right by the station.",
          location: "The Social Hub Amsterdam City, Wibautstraat 129, Amsterdam",
          url: "https://www.thesocialhub.co/amsterdam-city/" },
        { time: "19:30", title: "Dinner near the hotel", cat: "food",
          desc: "Keep it easy after the flight — see the Explore section for ideas.",
          explore: "Amsterdam" }
      ]
    },
    {
      date: "2026-08-21",
      label: "Day 2",
      theme: "City wandering & Van Gogh",
      desc: "Free morning exploring the centre, museum in the afternoon.",
      items: [
        { time: "10:00", title: "Explore the city", cat: "free",
          desc: "Canal ring, Dam Square, Jordaan, Nine Streets — or pick from the Explore section.",
          location: "Dam Square, Amsterdam",
          explore: "Amsterdam" },
        { time: "13:00", title: "Lunch", cat: "food",
          desc: "Wherever we end up — Fabel Friet or a stroopwafel stop are near the Nine Streets." },
        { time: "16:00", end: "18:00", title: "Van Gogh Museum", cat: "sight", booked: true,
          desc: "Timed entry at 16:00 — arrive ~15 min early with tickets ready on a phone.",
          location: "Van Gogh Museum, Amsterdam",
          url: "https://www.vangoghmuseum.nl/en" },
        { time: "19:00", title: "Dinner", cat: "food",
          desc: "Museum Quarter / De Pijp area is right there." }
      ]
    },
    {
      date: "2026-08-22",
      label: "Day 3",
      theme: "Dutch Grand Prix — Saturday 🏎️",
      desc: "Qualifying day at Circuit Zandvoort. It gets PACKED — leave early.",
      items: [
        { time: "08:30", title: "Train to Zandvoort aan Zee", cat: "travel",
          desc: "Direct train from Amsterdam Centraal (~30 min); extra GP trains run on race weekend but expect crowds. The circuit is a short walk from the station.",
          location: "Amsterdam Centraal" },
        { time: "10:00", title: "Circuit Zandvoort — qualifying day", cat: "sight", booked: true,
          desc: "Practice + qualifying. Bring earplugs (seriously), sunscreen and a rain layer — it's on the coast. Mostly cashless at the circuit.",
          location: "Circuit Zandvoort",
          url: "https://www.dutchgp.com/en/",
          explore: "Zandvoort" },
        { time: "18:30", title: "Train back + dinner", cat: "food",
          desc: "Expect queues for the train after the sessions end — grab food in Zandvoort if the line is crazy.",
          location: "Zandvoort aan Zee station" }
      ]
    },
    {
      date: "2026-08-23",
      label: "Day 4",
      theme: "Dutch Grand Prix — Race day 🏁",
      desc: "The big one. Same drill as Saturday, even busier.",
      items: [
        { time: "08:30", title: "Train to Zandvoort aan Zee", cat: "travel",
          desc: "Go early — race day crowds are the biggest of the weekend.",
          location: "Amsterdam Centraal" },
        { time: "10:00", title: "Circuit Zandvoort — RACE DAY", cat: "sight", booked: true,
          desc: "Support races in the morning, main race in the afternoon. Beach is right there if anyone needs a break from the noise.",
          location: "Circuit Zandvoort",
          url: "https://www.dutchgp.com/en/",
          explore: "Zandvoort" },
        { time: "19:00", title: "Head back & dinner", cat: "food",
          desc: "Patience for the trains — everyone leaves at once after the race." }
      ]
    },
    {
      date: "2026-08-24",
      label: "Day 5",
      theme: "Utrecht day trip",
      desc: "Slower day in the Netherlands' prettiest small city — 27 min by train.",
      items: [
        { time: "09:30", title: "Train to Utrecht Centraal", cat: "travel",
          desc: "Direct intercity from Amsterdam Centraal every ~10 min, 27 min ride. Also stops at Amstel station near the hotel.",
          location: "Amsterdam Centraal" },
        { time: "10:30", title: "Explore Utrecht", cat: "free",
          desc: "Canal wharves, Dom Tower, museums, lunch spots — everything is in the Explore section, filtered to Utrecht.",
          location: "Oudegracht, Utrecht",
          explore: "Utrecht" },
        { time: "18:00", title: "Train back to Amsterdam", cat: "travel",
          location: "Utrecht Centraal" }
      ]
    },
    {
      date: "2026-08-25",
      label: "Day 6",
      theme: "Free day",
      desc: "Nothing booked — pick whatever we fancy from the Explore section.",
      items: [
        { time: "10:00", title: "Open day — family's choice", cat: "free",
          desc: "Canal cruise? A'DAM Lookout? Vondelpark + bikes? Day at the beach? Open Explore and vote.",
          explore: "Amsterdam" },
        { time: "19:00", title: "Dinner", cat: "food",
          desc: "Good night to book somewhere nice — Moeders needs a reservation." }
      ]
    },
    {
      date: "2026-08-26",
      label: "Day 7",
      theme: "NEMO & last full day",
      desc: "Science museum in the morning, free afternoon for last wishes & souvenirs.",
      items: [
        { time: "10:00", end: "13:00", title: "NEMO Science Museum", cat: "sight", booked: true,
          desc: "Entry at 10:00. Five floors of hands-on experiments — don't miss the free rooftop terrace view.",
          location: "NEMO Science Museum, Amsterdam",
          url: "https://www.nemosciencemuseum.nl/en/" },
        { time: "13:30", title: "Lunch", cat: "food",
          desc: "NEMO rooftop café, or walk to the centre.",
          location: "NEMO Science Museum, Amsterdam" },
        { time: "15:00", title: "Free afternoon", cat: "free",
          desc: "Souvenirs (Bloemenmarkt for tulip bulbs), anything we missed, or just a canal-side ice cream.",
          explore: "Amsterdam" },
        { time: "19:00", title: "Farewell dinner", cat: "food",
          desc: "Last dinner in Amsterdam — make it count." }
      ]
    },
    {
      date: "2026-08-27",
      label: "Day 8",
      theme: "Fly home",
      desc: "Pack up, one last stroopwafel, and home. Times local again: Dutch → Cyprus.",
      items: [
        { time: "09:00", title: "Pack & check out", cat: "travel",
          location: "The Social Hub Amsterdam City, Wibautstraat 129, Amsterdam" },
        { time: "10:30", title: "Train to Schiphol", cat: "travel",
          desc: "Direct trains to Schiphol run from Amstel station (5 min walk from the hotel) — no need to go back to Centraal. Aim to be at Schiphol by ~11:15.",
          location: "Station Amsterdam Amstel" },
        { time: "13:35", title: "Flight: Amsterdam → Larnaca", cat: "travel", booked: true,
          desc: "Departs 13:35 Dutch time, lands 18:45 Cyprus time.",
          location: "Schiphol Airport" }
      ]
    }
  ],

  /* ---------- PLACES: the Explore catalog ---------- */

  places: [

    /* ===== AMSTERDAM — VISIT ===== */
    { name: "Rijksmuseum", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Museum Quarter", tags: ["art", "rainy day", "book ahead"],
      desc: "The Night Watch and 8000 more masterpieces. Book a time slot first.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/South_facade_of_the_Rijksmuseum_Amsterdam_%28DSCF0528%29.jpg/500px-South_facade_of_the_Rijksmuseum_Amsterdam_%28DSCF0528%29.jpg",
      lat: 52.3600, lng: 4.8852, location: "Rijksmuseum, Amsterdam",
      tickets: "https://www.rijksmuseum.nl/en/tickets", url: "https://www.rijksmuseum.nl/en" },
    { name: "Anne Frank House", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Jordaan", tags: ["history", "book ahead"],
      desc: "Moving and unmissable — but tickets release ~6 weeks ahead and vanish fast.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Amsterdam_%28NL%29%2C_Anne-Frank-Huis_--_2015_--_7185.jpg/500px-Amsterdam_%28NL%29%2C_Anne-Frank-Huis_--_2015_--_7185.jpg",
      lat: 52.3752, lng: 4.8840, location: "Anne Frank House, Amsterdam",
      tickets: "https://www.annefrank.org/en/museum/tickets/", url: "https://www.annefrank.org/en/" },
    { name: "Canal cruise", city: "Amsterdam", kind: "visit", category: "Activity",
      area: "Centre", tags: ["classic", "relaxing", "kids"],
      desc: "Open boat, ~75 minutes through the canal ring. The best first-look at the city.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png/500px-Imagen_de_los_canales_conc%C3%A9ntricos_en_%C3%81msterdam.png",
      lat: 52.3776, lng: 4.8987, location: "Prins Hendrikkade 25, Amsterdam",
      tickets: "https://www.lovers.nl/en/canal-cruises/" },
    { name: "Vondelpark", city: "Amsterdam", kind: "visit", category: "Park",
      area: "Museum Quarter", tags: ["outdoors", "free", "kids"],
      desc: "Amsterdam's Central Park. Playgrounds, ponds, and a pancake house in the middle. Rent bikes nearby.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Amsterdam%2C_Vondelpark%2C_at_the_pond-2.jpg/500px-Amsterdam%2C_Vondelpark%2C_at_the_pond-2.jpg",
      lat: 52.3579, lng: 4.8686, location: "Vondelpark, Amsterdam" },
    { name: "A'DAM Lookout swing", city: "Amsterdam", kind: "visit", category: "Viewpoint",
      area: "Noord", tags: ["thrill", "views"],
      desc: "Europe's highest swing, over the edge of a 100 m tower. Free ferry from Centraal.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Shell_Tower_Amsterdam-Noord_from_tour_boat_2016-09-12.jpg/500px-Shell_Tower_Amsterdam-Noord_from_tour_boat_2016-09-12.jpg",
      lat: 52.3840, lng: 4.9026, location: "A'DAM Lookout, Amsterdam",
      tickets: "https://www.adamlookout.com/tickets/", url: "https://www.adamlookout.com/" },
    { name: "Nine Streets", city: "Amsterdam", kind: "visit", category: "Neighbourhood",
      area: "Canal ring", tags: ["shopping", "free"],
      desc: "Nine little streets of boutiques, vintage shops and cafés between the canals.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Brug_24_in_de_Hartenstraat_over_de_Herengracht_foto_2.jpg/500px-Brug_24_in_de_Hartenstraat_over_de_Herengracht_foto_2.jpg",
      lat: 52.3693, lng: 4.8862, location: "De 9 Straatjes, Amsterdam" },
    { name: "Bloemenmarkt", city: "Amsterdam", kind: "visit", category: "Market",
      area: "Centre", tags: ["free", "quick stop", "souvenirs"],
      desc: "The floating flower market. Tulip bulbs make good souvenirs (check they're export-certified).",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/SingelBloemenmarkt.jpg/500px-SingelBloemenmarkt.jpg",
      lat: 52.3665, lng: 4.8913, location: "Bloemenmarkt, Amsterdam" },
    { name: "Albert Cuyp Markt", city: "Amsterdam", kind: "visit", category: "Market",
      area: "De Pijp", tags: ["free", "street food"],
      desc: "The city's biggest street market — and the home of fresh warm stroopwafels.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Albert_Cuypmarkt.jpg/500px-Albert_Cuypmarkt.jpg",
      lat: 52.3557, lng: 4.8934, location: "Albert Cuyp Markt, Amsterdam" },
    { name: "Jordaan wander", city: "Amsterdam", kind: "visit", category: "Neighbourhood",
      area: "Jordaan", tags: ["free", "photogenic"],
      desc: "The prettiest canals, hidden courtyards and brown cafés. Best on foot, no plan.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Eerste_Leliedwarsstraat.jpg/500px-Eerste_Leliedwarsstraat.jpg",
      lat: 52.3739, lng: 4.8809, location: "Jordaan, Amsterdam" },
    { name: "ARTIS Zoo", city: "Amsterdam", kind: "visit", category: "Zoo",
      area: "Plantage", tags: ["kids", "half day"],
      desc: "One of Europe's oldest zoos, right in the city. Combine with the Micropia microbe museum next door.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/NL-Artis-ingang.jpg/500px-NL-Artis-ingang.jpg",
      lat: 52.3663, lng: 4.9163, location: "ARTIS, Amsterdam",
      tickets: "https://www.artis.nl/en/plan-your-visit/tickets/", url: "https://www.artis.nl/en/" },
    { name: "Maritime Museum", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Oosterdok", tags: ["kids", "rainy day"],
      desc: "Climb aboard a full-size replica VOC sailing ship. 5 min walk from NEMO.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Nederlands_Scheepvaartmuseum_2024.jpg/500px-Nederlands_Scheepvaartmuseum_2024.jpg",
      lat: 52.3714, lng: 4.9153, location: "Het Scheepvaartmuseum, Amsterdam",
      url: "https://www.hetscheepvaartmuseum.com/" },
    { name: "Begijnhof", city: "Amsterdam", kind: "visit", category: "Landmark",
      area: "Centre", tags: ["free", "quiet", "quick stop"],
      desc: "A hidden medieval courtyard in the middle of the city. Enter quietly — people live here.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/BegijnhofAmsterdamPanorama.jpg/500px-BegijnhofAmsterdamPanorama.jpg",
      lat: 52.3689, lng: 4.8899, location: "Begijnhof, Amsterdam" },
    { name: "Body Worlds", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Damrak", tags: ["rainy day", "teens"],
      desc: "The anatomy exhibition — fascinating or gross depending who you ask. Good rainy-day backup.",
      lat: 52.3741, lng: 4.8934, location: "Body Worlds, Damrak 66, Amsterdam",
      url: "https://bodyworlds.nl/en/" },
    { name: "Westerpark", city: "Amsterdam", kind: "visit", category: "Park",
      area: "West", tags: ["outdoors", "free"],
      desc: "Big park + the Westergas culture complex: food, little festivals, space to run around.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Overzicht_Westerpark_met_eenden_en_fonteinen_-_Amsterdam_-_20536573_-_RCE.jpg/500px-Overzicht_Westerpark_met_eenden_en_fonteinen_-_Amsterdam_-_20536573_-_RCE.jpg",
      lat: 52.3866, lng: 4.8768, location: "Westerpark, Amsterdam" },
    { name: "This Is Holland", city: "Amsterdam", kind: "visit", category: "Activity",
      area: "Noord", tags: ["thrill", "kids", "rainy day"],
      desc: "5D 'flight' over the Netherlands — you hang in front of a giant dome screen. Short, fun, next to A'DAM tower.",
      lat: 52.3843, lng: 4.9017, location: "This Is Holland, Amsterdam",
      tickets: "https://www.thisisholland.com/", url: "https://www.thisisholland.com/" },
    { name: "Heineken Experience", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "De Pijp", tags: ["adults", "rainy day"],
      desc: "Interactive tour of the original brewery, two drinks included. 18+ vibes — one for the grown-ups.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Former_Heineken_Brewery_in_Amsterdam.jpg/500px-Former_Heineken_Brewery_in_Amsterdam.jpg",
      lat: 52.3578, lng: 4.8919, location: "Heineken Experience, Amsterdam",
      tickets: "https://www.heinekenexperience.com/", url: "https://www.heinekenexperience.com/" },
    { name: "Royal Palace", city: "Amsterdam", kind: "visit", category: "Landmark",
      area: "Dam Square", tags: ["history", "rainy day"],
      desc: "The king's official palace, open to visit when not in use — surprisingly opulent inside.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Palacio_Real%2C_%C3%81msterdam%2C_Pa%C3%ADses_Bajos%2C_2016-05-30%2C_DD_07-09_HDR.jpg/500px-Palacio_Real%2C_%C3%81msterdam%2C_Pa%C3%ADses_Bajos%2C_2016-05-30%2C_DD_07-09_HDR.jpg",
      lat: 52.3731, lng: 4.8913, location: "Royal Palace Amsterdam",
      url: "https://www.paleisamsterdam.nl/en/" },
    { name: "Rembrandt House", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Waterlooplein", tags: ["art", "history"],
      desc: "Rembrandt's actual house and studio, restored as he had it. Small, personal, great with the audio tour.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Rembrandshuis.jpg/500px-Rembrandshuis.jpg",
      lat: 52.3694, lng: 4.9012, location: "Museum Het Rembrandthuis, Amsterdam",
      url: "https://www.rembrandthuis.nl/en/" },
    { name: "Micropia", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "Plantage", tags: ["kids", "science", "rainy day"],
      desc: "The world's only microbe museum — weirdly fascinating. Next to ARTIS, combo tickets exist.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Micropia_Museum_Amsterdam_4.jpg/500px-Micropia_Museum_Amsterdam_4.jpg",
      lat: 52.3671, lng: 4.9127, location: "Micropia, Amsterdam",
      url: "https://www.micropia.nl/en/" },
    { name: "STRAAT museum", city: "Amsterdam", kind: "visit", category: "Museum",
      area: "NDSM, Noord", tags: ["street art", "teens"],
      desc: "Huge street-art museum in a former shipyard warehouse. Take the free NDSM ferry — half the fun.",
      lat: 52.4012, lng: 4.8935, location: "STRAAT Museum, Amsterdam",
      tickets: "https://straatmuseum.com/en/tickets", url: "https://straatmuseum.com/" },
    { name: "NDSM wharf", city: "Amsterdam", kind: "visit", category: "Neighbourhood",
      area: "Noord", tags: ["free", "street art", "ferry ride"],
      desc: "Old shipyard turned creative playground: murals, container homes, city beach. Free 15-min ferry from Centraal.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Pontkade_III_Amsterdam.jpg/500px-Pontkade_III_Amsterdam.jpg",
      lat: 52.4013, lng: 4.8944, location: "NDSM, Amsterdam" },
    { name: "Hortus Botanicus", city: "Amsterdam", kind: "visit", category: "Park",
      area: "Plantage", tags: ["quiet", "greenhouses"],
      desc: "One of the world's oldest botanical gardens (1638) — butterfly greenhouse, calm café.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/De_Plantage_%2817%29.jpg/500px-De_Plantage_%2817%29.jpg",
      lat: 52.3667, lng: 4.9078, location: "Hortus Botanicus, Amsterdam",
      url: "https://www.dehortus.nl/en/" },
    { name: "Magere Brug", city: "Amsterdam", kind: "visit", category: "Landmark",
      area: "Amstel", tags: ["free", "quick stop", "photogenic"],
      desc: "The 'Skinny Bridge' over the Amstel — prettiest at dusk when it lights up. 15 min walk from the hotel.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Magere_brug_amsterdam.jpg/500px-Magere_brug_amsterdam.jpg",
      lat: 52.3638, lng: 4.9022, location: "Magere Brug, Amsterdam" },
    { name: "OBA library rooftop", city: "Amsterdam", kind: "visit", category: "Viewpoint",
      area: "Oosterdok", tags: ["free", "views", "rainy day"],
      desc: "Top floor of the public library: free skyline view + café. Right next to NEMO — perfect combo stop.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/BibliotheekOBA_2.jpg/500px-BibliotheekOBA_2.jpg",
      lat: 52.3762, lng: 4.9086, location: "OBA Oosterdok, Amsterdam" },
    { name: "Zaanse Schans", city: "Amsterdam", kind: "visit", category: "Day trip",
      area: "Zaandam (20 min train)", tags: ["windmills", "half day", "kids"],
      desc: "THE windmill postcard village: working mills, clog & cheese demos. Free to wander, mills charge small entry. Train from Centraal + short walk.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Zaanstad_Zaanse_Schans_22.jpg/500px-Zaanstad_Zaanse_Schans_22.jpg",
      lat: 52.4736, lng: 4.8177, location: "Zaanse Schans",
      url: "https://www.dezaanseschans.nl/en/" },

    /* ===== AMSTERDAM — EAT ===== */
    { name: "Moeders", city: "Amsterdam", kind: "eat", category: "Dutch",
      area: "Jordaan", price: "€€", tags: ["dinner", "book ahead"],
      desc: "Classic Dutch home cooking, walls covered in photos of mothers. Book ahead!",
      lat: 52.3735, lng: 4.8785, location: "Moeders, Rozengracht 251, Amsterdam",
      url: "https://www.moeders.com/" },
    { name: "Foodhallen", city: "Amsterdam", kind: "eat", category: "Food court",
      area: "Oud-West", price: "€€", tags: ["lunch", "dinner", "something for everyone"],
      desc: "Indoor food market with 20+ stands — perfect when everyone wants something different.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/De_Hallen_Amsterdam_2024_Entree_Tollensstraat.jpg/500px-De_Hallen_Amsterdam_2024_Entree_Tollensstraat.jpg",
      lat: 52.3667, lng: 4.8686, location: "Foodhallen, Amsterdam", url: "https://foodhallen.nl/" },
    { name: "The Pancake Bakery", city: "Amsterdam", kind: "eat", category: "Pancakes",
      area: "Prinsengracht", price: "€€", tags: ["kids", "lunch"],
      desc: "75 kinds of Dutch pancakes in an old canal warehouse. Near Anne Frank House.",
      lat: 52.3763, lng: 4.8845, location: "The Pancake Bakery, Amsterdam", url: "https://pancake.nl/" },
    { name: "Winkel 43", city: "Amsterdam", kind: "eat", category: "Café",
      area: "Jordaan", price: "€", tags: ["apple pie", "snack"],
      desc: "THE apple pie. Expect a queue on weekends — worth it.",
      lat: 52.3796, lng: 4.8865, location: "Winkel 43, Noordermarkt, Amsterdam", url: "https://winkel43.nl/" },
    { name: "Fabel Friet", city: "Amsterdam", kind: "eat", category: "Fries",
      area: "Nine Streets", price: "€", tags: ["snack", "famous"],
      desc: "The famous crispy fries with melted cheese. The line moves fast.",
      lat: 52.3690, lng: 4.8849, location: "Fabel Friet, Runstraat, Amsterdam" },
    { name: "Vleminckx Sausmeesters", city: "Amsterdam", kind: "eat", category: "Fries",
      area: "Centre", price: "€", tags: ["snack", "since 1957"],
      desc: "The other legendary fries wall — Amsterdammers argue about which is best. Try both, settle it.",
      lat: 52.3688, lng: 4.8905, location: "Vleminckx, Voetboogstraat, Amsterdam" },
    { name: "Van Stapele Koekmakerij", city: "Amsterdam", kind: "eat", category: "Bakery",
      area: "Centre", price: "€", tags: ["snack", "one thing only"],
      desc: "Sells exactly one thing: a warm dark-chocolate cookie with white chocolate inside. Often sold out by afternoon.",
      lat: 52.3697, lng: 4.8907, location: "Van Stapele, Heisteeg 4, Amsterdam", url: "https://vanstapele.com/" },
    { name: "Kam Yin", city: "Amsterdam", kind: "eat", category: "Surinamese",
      area: "Centre", price: "€", tags: ["lunch", "cheap & good"],
      desc: "Cheap, fast and delicious Surinamese-Chinese — try the roti or a broodje pom.",
      lat: 52.3757, lng: 4.8977, location: "Kam Yin, Warmoesstraat, Amsterdam" },
    { name: "The Seafood Bar", city: "Amsterdam", kind: "eat", category: "Seafood",
      area: "Centre", price: "€€€", tags: ["dinner", "fish"],
      desc: "Bright, busy seafood place — great fruits de mer and fish & chips.",
      lat: 52.3679, lng: 4.8896, location: "The Seafood Bar, Spui, Amsterdam",
      url: "https://www.theseafoodbar.com/" },
    { name: "Café de Klos", city: "Amsterdam", kind: "eat", category: "Grill",
      area: "Leidseplein", price: "€€", tags: ["dinner", "ribs", "no reservations"],
      desc: "Legendary spare ribs in a tiny smoky bar. No bookings — go early or queue.",
      lat: 52.3629, lng: 4.8834, location: "Café de Klos, Kerkstraat 41, Amsterdam" },
    { name: "Bakers & Roasters", city: "Amsterdam", kind: "eat", category: "Brunch",
      area: "De Pijp", price: "€€", tags: ["breakfast", "brunch"],
      desc: "Kiwi/Brazilian brunch spot — banana bread french toast worth getting up for.",
      lat: 52.3562, lng: 4.8890, location: "Bakers & Roasters, Amsterdam",
      url: "https://www.bakersandroasters.com/" },
    { name: "Sea Palace", city: "Amsterdam", kind: "eat", category: "Chinese",
      area: "Oosterdok", price: "€€", tags: ["dinner", "floating restaurant", "kids"],
      desc: "A giant floating pagoda restaurant — the novelty alone is worth it, dim sum is solid. Near NEMO.",
      lat: 52.3746, lng: 4.9075, location: "Sea Palace, Amsterdam", url: "https://seapalace.nl/en/" },
    { name: "FEBO", city: "Amsterdam", kind: "eat", category: "Snacks",
      area: "Everywhere", price: "€", tags: ["snack", "experience", "kids"],
      desc: "Hot snacks from a wall of vending hatches — a Dutch rite of passage. Get a kroket.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Amsterdam_-_Nieuwendijk_-_Febo.jpg/500px-Amsterdam_-_Nieuwendijk_-_Febo.jpg",
      lat: 52.3730, lng: 4.8926, location: "FEBO Damrak, Amsterdam" },
    { name: "Van Wonderen Stroopwafels", city: "Amsterdam", kind: "eat", category: "Bakery",
      area: "Kalverstraat", price: "€", tags: ["snack", "stroopwafel", "kids"],
      desc: "Fresh warm stroopwafels with over-the-top toppings. Touristy? Yes. Delicious? Also yes.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Stroopwafels_01.jpg/500px-Stroopwafels_01.jpg",
      lat: 52.3679, lng: 4.8903, location: "Van Wonderen Stroopwafels, Kalverstraat, Amsterdam" },
    { name: "Massimo Gelato", city: "Amsterdam", kind: "eat", category: "Ice cream",
      area: "De Pijp", price: "€", tags: ["snack", "kids", "the best"],
      desc: "Widely considered the best gelato in Amsterdam — proper Italian, pistachio is the test.",
      lat: 52.3542, lng: 4.8965, location: "Massimo Gelato, Van Ostadestraat, Amsterdam" },
    { name: "Bazar", city: "Amsterdam", kind: "eat", category: "Middle Eastern",
      area: "Albert Cuyp", price: "€€", tags: ["lunch", "dinner", "kids", "fun interior"],
      desc: "Middle-Eastern food inside a gorgeously converted old church in the middle of the market street.",
      lat: 52.3556, lng: 4.8951, location: "Bazar Amsterdam, Albert Cuypstraat",
      url: "https://www.bazaramsterdam.nl/" },
    { name: "La Perla", city: "Amsterdam", kind: "eat", category: "Pizza",
      area: "Jordaan", price: "€€", tags: ["lunch", "dinner", "kids"],
      desc: "Wood-oven Neapolitan pizza in the heart of the Jordaan — takeaway to eat by the canal, or table service across the street.",
      lat: 52.3776, lng: 4.8828, location: "Pizzeria La Perla, Jordaan, Amsterdam",
      url: "https://pizzaperla.nl/" },
    { name: "Pllek", city: "Amsterdam", kind: "eat", category: "Beach club",
      area: "NDSM, Noord", price: "€€", tags: ["dinner", "sunset", "city beach"],
      desc: "Restaurant built from shipping containers with a little city beach and skyline sunset views. Pairs with STRAAT.",
      lat: 52.4045, lng: 4.8896, location: "Pllek, NDSM, Amsterdam", url: "https://pllek.nl/" },
    { name: "Pannenkoekenboot", city: "Amsterdam", kind: "eat", category: "Pancakes",
      area: "NDSM, Noord", price: "€€", tags: ["kids", "boat", "all you can eat"],
      desc: "All-you-can-eat pancake buffet ON A BOAT cruising the IJ for ~75 min. Peak kid happiness. Book ahead.",
      lat: 52.4003, lng: 4.8942, location: "Pannenkoekenboot, NDSM, Amsterdam",
      tickets: "https://www.pannenkoekenboot.nl/", url: "https://www.pannenkoekenboot.nl/" },

    /* ===== UTRECHT — VISIT ===== */
    { name: "Dom Tower", city: "Utrecht", kind: "visit", category: "Landmark",
      area: "Old town", tags: ["views", "book ahead"],
      hours: "Guided climbs daily — book a time slot online",
      desc: "Tallest church tower in NL — 465 steps, amazing view. Guided climbs only, book a slot.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/DomTorenUtrechtNederland.jpg/500px-DomTorenUtrechtNederland.jpg",
      lat: 52.0907, lng: 5.1214, location: "Domtoren, Utrecht",
      tickets: "https://www.domtoren.nl/en/tickets", url: "https://www.domtoren.nl/en" },
    { name: "Oudegracht wharves", city: "Utrecht", kind: "visit", category: "Landmark",
      area: "Old town", tags: ["free", "photogenic"],
      desc: "Utrecht's signature: canals with wharf cellars at water level, now cafés and shops.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Utrecht_Canals_Aerial_View_-_July_2006.jpg/500px-Utrecht_Canals_Aerial_View_-_July_2006.jpg",
      lat: 52.0894, lng: 5.1204, location: "Oudegracht, Utrecht" },
    { name: "Railway Museum", city: "Utrecht", kind: "visit", category: "Museum",
      area: "Maliebaan", tags: ["kids", "trains", "half day"],
      hours: "10–17 · OPEN our Monday (school-holiday Mondays)",
      desc: "Het Spoorwegmuseum — real locomotives, rides and simulators in a grand old station. Big hit with kids.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Rijksmonument-36180.jpg/500px-Rijksmonument-36180.jpg",
      lat: 52.0876, lng: 5.1310, location: "Spoorwegmuseum, Utrecht",
      tickets: "https://www.spoorwegmuseum.nl/en/plan-your-visit/", url: "https://www.spoorwegmuseum.nl/en/" },
    { name: "Miffy Museum", city: "Utrecht", kind: "visit", category: "Museum",
      area: "Museum quarter", tags: ["little kids", "book ahead"],
      hours: "Tue–Sun 10–17 · ⚠️ CLOSED our Monday",
      desc: "Miffy (nijntje) was born in Utrecht. Aimed at ages 2–6. NOTE: closed Mondays — so not on our Utrecht day.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Dick_Bruna_huis.jpg/500px-Dick_Bruna_huis.jpg",
      lat: 52.0851, lng: 5.1215, location: "Nijntje Museum, Utrecht",
      tickets: "https://nijntjemuseum.nl/en/", url: "https://nijntjemuseum.nl/en/" },
    { name: "Centraal Museum", city: "Utrecht", kind: "visit", category: "Museum",
      area: "Museum quarter", tags: ["art", "rainy day"],
      hours: "Tue–Sun 11–17 · ⚠️ CLOSED our Monday",
      desc: "Utrecht's main museum: art, design and the world's largest Rietveld collection. NOTE: closed Mondays — so not on our Utrecht day.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Exterieur_Centraal_Museum.jpg/500px-Exterieur_Centraal_Museum.jpg",
      lat: 52.0846, lng: 5.1211, location: "Centraal Museum, Utrecht",
      url: "https://www.centraalmuseum.nl/en" },
    { name: "Canal pedal boats", city: "Utrecht", kind: "visit", category: "Activity",
      area: "Old town", tags: ["outdoors", "kids"],
      desc: "Rent a pedal boat or canoe and see the wharves from water level.",
      lat: 52.0894, lng: 5.1204, location: "Kanoverhuur Utrecht, Oudegracht" },
    { name: "DOMunder", city: "Utrecht", kind: "visit", category: "Museum",
      area: "Domplein", tags: ["history", "underground", "book ahead"],
      hours: "Timed tours only — book online & check Monday slots (some tours Dutch-only)",
      desc: "Descend under Dom square with a torch-flashlight to find 2000 years of buried city — Roman fort included. Surprisingly great for kids.",
      lat: 52.0905, lng: 5.1218, location: "DOMunder, Utrecht",
      tickets: "https://www.domunder.nl/", url: "https://www.domunder.nl/" },
    { name: "Museum Speelklok", city: "Utrecht", kind: "visit", category: "Museum",
      area: "Old town", tags: ["kids", "music", "rainy day"],
      hours: "10–17 · OPEN our Monday (school-holiday Mondays)",
      desc: "Self-playing musical machines from music boxes to giant street organs — the guided demo tour is joyful.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Buurkerk_en_Dom.jpg/500px-Buurkerk_en_Dom.jpg",
      lat: 52.0914, lng: 5.1183, location: "Museum Speelklok, Utrecht",
      url: "https://www.museumspeelklok.nl/" },
    { name: "Botanic Gardens", city: "Utrecht", kind: "visit", category: "Park",
      area: "Science Park", tags: ["outdoors", "quiet"],
      hours: "Daily 10–16:30 (Mar–Nov)",
      desc: "University botanical gardens built around an old fort — rock garden, butterflies, picnic-friendly.",
      lat: 52.0851, lng: 5.1725, location: "Botanische Tuinen Universiteit Utrecht",
      url: "https://www.uu.nl/en/botanic-gardens" },
    { name: "Castle De Haar", city: "Utrecht", kind: "visit", category: "Landmark",
      area: "Haarzuilens (30 min bus)", tags: ["castle", "half day"],
      hours: "Daily: park 9–17, castle from 11 — book a time slot",
      desc: "The Netherlands' biggest, most fairy-tale castle with grand gardens. Needs a bus/taxi from Utrecht — only if we fancy a detour.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/De_Haar_castlle.jpg/500px-De_Haar_castlle.jpg",
      lat: 52.1219, lng: 4.9855, location: "Kasteel de Haar, Haarzuilens",
      tickets: "https://www.kasteeldehaar.nl/english/", url: "https://www.kasteeldehaar.nl/english/" },

    /* ===== UTRECHT — EAT ===== */
    { name: "Broodje Mario", city: "Utrecht", kind: "eat", category: "Sandwiches",
      area: "Old town", price: "€", tags: ["lunch", "famous", "quick"],
      desc: "The legendary Italian sandwich of Utrecht — locals queue for it since 1974.",
      lat: 52.0929, lng: 5.1178, location: "Broodje Mario, Oudegracht 130, Utrecht" },
    { name: "Winkel van Sinkel", city: "Utrecht", kind: "eat", category: "Grand café",
      area: "Old town", price: "€€", tags: ["lunch", "dinner", "landmark"],
      desc: "Grand café in a huge 19th-century department store on the canal. Nice terrace on the wharf.",
      lat: 52.0910, lng: 5.1197, location: "Winkel van Sinkel, Utrecht",
      url: "https://www.dewinkelvansinkel.nl/" },
    { name: "Olivier", city: "Utrecht", kind: "eat", category: "Belgian café",
      area: "Old town", price: "€€", tags: ["dinner", "in a church"],
      desc: "Belgian beer café inside a converted hidden church — huge and atmospheric, decent burgers and stews.",
      lat: 52.0937, lng: 5.1156, location: "Belgisch Biercafé Olivier, Utrecht" },
    { name: "The Village Coffee", city: "Utrecht", kind: "eat", category: "Café",
      area: "Voorstraat", price: "€", tags: ["coffee", "snack"],
      desc: "Utrecht's favourite specialty coffee stop, good cakes.",
      lat: 52.0936, lng: 5.1229, location: "The Village Coffee, Voorstraat 46, Utrecht" },
    { name: "De Frietwinkel", city: "Utrecht", kind: "eat", category: "Fries",
      area: "Twijnstraat", price: "€", tags: ["snack", "kids"],
      desc: "Utrecht's answer to the Amsterdam fries wars — fresh-cut, proper sauces, always a small queue.",
      lat: 52.0852, lng: 5.1233, location: "De Frietwinkel, Twijnstraat, Utrecht" },
    { name: "Roberto Gelato", city: "Utrecht", kind: "eat", category: "Ice cream",
      area: "Twijnstraat", price: "€", tags: ["snack", "kids", "the best"],
      desc: "Legendary gelateria — Utrechters queue around the corner on sunny days. Two doors from De Frietwinkel: fries then ice cream.",
      lat: 52.0854, lng: 5.1235, location: "IJssalon Roberto Gelato, Utrecht" },

    /* ===== ZANDVOORT ===== */
    { name: "Circuit Zandvoort", city: "Zandvoort", kind: "visit", category: "Activity",
      area: "Circuit", tags: ["GP weekend"],
      desc: "Where we'll be Sat + Sun for the Dutch GP. Short walk from the station.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Zandvoort_Circuit.png/500px-Zandvoort_Circuit.png",
      lat: 52.3888, lng: 4.5409, location: "Circuit Zandvoort",
      url: "https://www.dutchgp.com/en/" },
    { name: "Zandvoort beach", city: "Zandvoort", kind: "visit", category: "Beach",
      area: "Boulevard", tags: ["outdoors", "kids", "free"],
      desc: "Wide sandy North Sea beach, right next to the circuit. Beach clubs all along.",
      lat: 52.3731, lng: 4.5289, location: "Zandvoort aan Zee beach" },
    { name: "Zuid-Kennemerland dunes", city: "Zandvoort", kind: "visit", category: "Park",
      area: "North of town", tags: ["outdoors", "free", "wildlife"],
      desc: "National park of wild dunes between Zandvoort and Haarlem — walking trails, and with luck you'll spot the European bison herd from the lookout.",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Duinen_in_Nationaal_Park_Zuid-Kennemerland.jpg/500px-Duinen_in_Nationaal_Park_Zuid-Kennemerland.jpg",
      lat: 52.4005, lng: 4.5741, location: "Nationaal Park Zuid-Kennemerland" },
    { name: "Beach pavilion dinner", city: "Zandvoort", kind: "eat", category: "Beach club",
      area: "Boulevard", price: "€€", tags: ["dinner", "sunset"],
      desc: "Dozens of beach pavilions on the sand — pick any for dinner with a sunset over the sea after the racing.",
      lat: 52.3740, lng: 4.5300, location: "Strandpaviljoens Zandvoort" }
  ],

  info: [
    { icon: "🚋", title: "Getting around",
      desc: "Trams, metros and trains: tap in AND out with any contactless debit/credit card (OVpay). Or just walk — the centre is small." },
    { icon: "🏎️", title: "GP weekend travel",
      desc: "Sat 22 + Sun 23 Aug: direct trains Amsterdam Centraal → Zandvoort aan Zee (~30 min). Go EARLY, expect big queues coming back. Circuit is mostly cashless." },
    { icon: "🚲", title: "Watch the bike lanes!",
      desc: "Red/brown pavement = bike lane. Cyclists have right of way and they do NOT slow down. Look both ways twice." },
    { icon: "💶", title: "Paying",
      desc: "Cards work everywhere; many places are card-only. Some market stalls prefer cash — keep €20–30 in small notes." },
    { icon: "☔", title: "Weather",
      desc: "Amsterdam weather changes by the hour. Light rain jacket every day, even if the morning looks sunny — especially at the coast in Zandvoort." },
    { icon: "🕐", title: "Time zones",
      desc: "Netherlands is 1 hour behind Cyprus. All times in this schedule are local to wherever we are at that moment." },
    { icon: "📱", title: "Add to Home Screen",
      desc: "Open this site in Safari/Chrome → Share → 'Add to Home Screen'. It becomes an app icon and keeps working offline — handy at the circuit where the network dies." },
    { icon: "🆘", title: "Emergency",
      desc: "112 for police/ambulance/fire (EU-wide). Pharmacies are called 'apotheek'." }
  ]
};
